### ISSUE TITLE
Syntax errors on python 3.7

### ISSUE THREAD

**Issue by muhlemmer** [Mailu/Podop#2]
While working on Mailu/Mailu#680, in an attempt to make more common images, dovecot and postfix got upgraded to python 3.7. Upon running, I've seen the following error (same on both containers)

```
[tim@sky ~]$ docker logs 9c917cd8a4cc
Traceback (most recent call last):
  File "/start.py", line 12, in <module>
    from podop import run_server
  File "/usr/local/lib/python3.7/site-packages/podop/__init__.py", line 10, in <module>
    from podop import postfix, dovecot, table
  File "/usr/local/lib/python3.7/site-packages/podop/postfix.py", line 94
    return asyncio.async(self.process_request(name, key))
                       ^
SyntaxError: invalid syntax
```
Workaround for now is to use python 3.6 for all images.

**Comment by muhlemmer** [comment]
With the latest development in aboved mentioned PR, as small note. The latest stable version of python in `alpine:3.8` is 3.6.6. So for now it does not create a direct issue. This will become an issue when an upgrade to python 3.7 happens.

**Comment by blinkeye** [comment]
Which means that it's related/needed for https://github.com/Mailu/Mailu/pull/1052 ? Because `alpine:3.10` now has [Python v3.7.3](https://pkgs.alpinelinux.org/packages?name=python*&branch=v3.10)

**Comment by blinkeye** [comment]
Ah, I think we can close this issue now because #6 has been merged (and addresses the reported problem).

**Comment by kaiyou** [comment]
Indeed.
