### ISSUE TITLE
How to integrate podop with mailman?

### ISSUE THREAD

**Issue by belegnar** [Mailu/Podop#5]
*

**Comment by blinkeye** [comment]
Could you provide more details? Is your intention to integrate `mailman` in Mailu? (Please fix your title: you probably mean mai**l**man?)

**Comment by belegnar** [comment]
Yes, i've integrated mailman3 with Mailu, but it does not look very pretty for now.

**Comment by ghostwheel42** [comment]
This issue belongs into the Mailu project.
